### ISSUE TITLE
raco test --timeout <n> seems to be ignored. 

### ISSUE THREAD

**Issue by florence** [racket/compiler#4]
Migrating https://github.com/plt/racket/issues/944

This looks like it happened in 16509fa8, specifically with https://github.com/racket/compiler/commit/16509fa8e832d11dc103befb2ce8f7f4a6139db7#diff-fc4e46f41d81aba430efe0cce98cb399R754 which ignores the default timeout. Its weird that this has gone unnoticed for so long, since the DrDr timeouts would no longer work.

I'll have a PR for this up soon.

**Comment by mflatt** [comment]
DrDr imposes its own timeout, so that's why the problem survived by for so long. I had suspected a problem a few times, but never when I had time to investigate.
Thanks for the repair!
